name: Run download_chirps_gefs script

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 9 * * *'
  push:
    branches:
      - chirps-download
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this if your dependencies are listed elsewhere

    - name: Run script
      env:
        DEV_BLOB_SAS: ${{ secrets.DEV_BLOB_SAS }}
        PROD_BLOB_SAS: ${{ secrets.PROD_BLOB_SAS }}
      run: |
        python update_chirps_gefs.py
